### ISSUE TITLE
forecast function not working properly due to conflicts with smooth

### ISSUE THREAD

**Issue by xiesong** [trnnick/mapa#2]
I get following error when I use forecast function. The problem arises due to conflict with "smooth" package. I need to use smooth package because "MAPA" package requires it.

Error in UseMethod("forecast") :
no applicable method for 'forecast' applied to an object of class "c('ARIMA', 'Arima')"

**Comment by trnnick** [comment]
Cam you provide an example where ths happens? I am not able to replicate the error. The forecast function is only called internally in MAPA and does not call it on ARIMA models. Also the smooth package will only be called when you try to forecast series with more than 24 periods in a season.

**Comment by xiesong** [comment]
Sure below for the example,the code below runs fine when I detach smooth and MAPA. 

> forecast(auto.arima(AirPassengers), h = 12)$mean
Error in UseMethod("forecast") : 
  no applicable method for 'forecast' applied to an object of class "c('ARIMA', 'Arima')"



here is what I see in the console when I selecte MAPA/smooth

The following object is masked from ‘package:forecast’:

    forecast

**Comment by trnnick** [comment]
I tried the following and it still works fine for me. I am using the latest version of all packages (MAPA, forecast, smooth).
`library(MAPA)`
`forecast(auto.arima(AirPassengers), h = 12)$mean`

**Comment by xiesong** [comment]
As soon as I installed latest version of package "smooth" the issue has been resolved. 

Please close this issue.

Thanks for your help.
