### ISSUE TITLE
"NA"s forecast produced by mapa when type = "es"

### ISSUE THREAD

**Issue by xiesong** [trnnick/mapa#3]
When I use new version of "smooth" package and use type = "es", I get "NAs" in the forecast see below for reproducible example.

> library(MAPA)
Loading required package: smooth
This is package "smooth", v2.3.0
> library(smooth)
> mapa(AirPassengers,type = "ets")
MAPA fit MSE: 255.5, MAE: 12.01
Out-of-samplpe forecasts:
     t+1      t+2      t+3      t+4      t+5      t+6      t+7      t+8      t+9     t+10     t+11     t+12 
453.6950 448.4034 490.8737 490.2953 511.0565 551.2463 613.2886 612.4266 537.6973 480.5092 437.6717 468.0141 
> mapa(AirPassengers,type = "es")
Error in plot.window(...) : need finite 'ylim' values

**Comment by trnnick** [comment]
Thanks for spotting this. This was due to a recent change in the smooth package that I missed. Now fixed! Updated here and soon available on CRAN as well.

**Comment by xiesong** [comment]
thank you
